USE VeteransMuseum;
ALTER TABLE veterans
ADD COLUMN Addinfo1PicLoc VARCHAR(250),
ADD COLUMN Addinfo2PicLoc VARCHAR(250),
ADD COLUMN AddInfo3PicLoc VARCHAR(250),
ADD COLUMN AddInfo4PicLoc VARCHAR(250);